### ISSUE TITLE
add tests for upgrading the KUDO Kafka 

### ISSUE THREAD

**Issue by zmalik** [mesosphere/kudo-kafka-operator#22]
add tests to upgrade the KUDO Kafka

**Comment by mpereira** [comment]
KUDO C* has upgrade tests if you're thinking of doing something similar:

- Integration test:
  - Section that installs a KUDO operator: https://github.com/mesosphere/kudo-cassandra-operator/blob/4517807137461f3308d82cf68bdd619ec9e50bc6/tests/suites/sanity_test.go#L46-L60
  - Section that upgrades the KUDO operator instance: https://github.com/mesosphere/kudo-cassandra-operator/blob/4517807137461f3308d82cf68bdd619ec9e50bc6/tests/suites/sanity_test.go#L62-L76
- Testing library function that does the upgrade:
  - https://github.com/mesosphere/kudo-cassandra-operator/blob/4517807137461f3308d82cf68bdd619ec9e50bc6/tests/utils/kudo/kudo.go#L329-L339
  - https://github.com/mesosphere/kudo-cassandra-operator/blob/4517807137461f3308d82cf68bdd619ec9e50bc6/tests/utils/kudo/kudo.go#L247-L315
